# Generated by Django 6.1.1 on 2026-09-14 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting_created", "Meeting Created"),
                            ("meeting_processed", "Meeting Processed"),
                            ("transcription_completed", "Transcription Completed"),
                            ("analysis_completed", "Analysis Completed"),
                            ("task_created", "Task Created"),
                            ("task_completed", "Task Completed"),
                            ("qa_query", "Q&A Query"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
