# Generated by Django 6.1.1 on 2026-09-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("executive_summary", models.TextField()),
                ("key_points", models.JSONField(default=list)),
                ("sentiment", models.JSONField(default=dict)),
                ("topics", models.JSONField(default=list)),
                ("unresolved_issues", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_summaries",
            },
        ),
    ]
