# Generated by Django 6.1.1 on 2026-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_id", models.IntegerField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("transcription", "Transcription"),
                            ("diarization", "Diarization"),
                            ("summarization", "Summarization"),
                            ("action_extraction", "Action Extraction"),
                            ("decision_extraction", "Decision Extraction"),
                            ("sentiment_analysis", "Sentiment Analysis"),
                            ("embedding_generation", "Embedding Generation"),
                            ("qa_query", "Q&A Query"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "processing_time",
                    models.FloatField(
                        help_text="Processing time in seconds", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_processing_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
