# Generated by Django 6.1.1 on 2026-09-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_label", models.CharField(max_length=50)),
                ("speaker_name", models.CharField(blank=True, max_length=100)),
                ("text", models.TextField()),
                ("start_time", models.FloatField(help_text="Start time in seconds")),
                ("end_time", models.FloatField(help_text="End time in seconds")),
                ("confidence", models.FloatField(default=0.0)),
                ("order", models.IntegerField()),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "transcript_segments",
                "ordering": ["start_time"],
            },
        ),
    ]
